#Create/Adapt Behave file 
# which includes rank, rank certainty, proximity weighted degree centrality, weighted indegree of agonistic actions
# viggilance rates and self-directed rates

######################################################
#Complete behav file
######################################################

library(dplyr)
setwd("C:/Users/Camille Testard/Documents/GitHub/Cayo-Maria")# set working directory

#Load current behav file
behav  <- read.csv("behav.txt")
names(behav)[3]= "year_behav"
names(behav)[2]= "id"
#Only select groups and years of interest
behav <- behav[which((behav$year_behav == 2016 & behav$Group == "HH" | behav$year_behav == 2017 & behav$Group == "KK")),]
behav2 = behav #For later check

#1. Replace and complete ranking and rc info
#Load Lauren computed rank
HHrankF_lauren = read.csv("Behavioral_Data/GroupHH2016_files/Dominance_females_lauren.csv"); names(HHrankF_lauren)[1]='id' 
HHrankF_lauren$id = as.character(HHrankF_lauren$id)
HHrankF_lauren$id <- sub(" ", "", HHrankF_lauren$id) #eliminate spaces in names
HHrankF_lauren$id <- sub(" ", "", HHrankF_lauren$id) #eliminate spaces in names
HHrankM_lauren = read.csv("Behavioral_Data/GroupHH2016_files/Dominance_males_lauren.csv"); names(HHrankM_lauren)[1]='id' 
HHrankM_lauren$id <- sub(" ", "", HHrankM_lauren$id) #eliminate spaces in names
HHrankM_lauren$id <- sub(" ", "", HHrankM_lauren$id) #eliminate spaces in names

idx = sapply( seq_along (as.character(HHrankF_lauren$id)), #find the indices of lauren's rank info for females in the behavioral file 
               function(i){which(as.character(HHrankF_lauren$id[i])==as.character(behav$id))} )
idxF_lauren = data.frame(matrix(unlist(idx), nrow=length(idx), byrow=T)); colnames(idxF_lauren)="index" #transform into dataframe
behav$rank[idxF_lauren$index]=HHrankF_lauren$percent #replace values
               
idx = sapply( seq_along (as.character(HHrankM_lauren$id)), 
              function(i){which(as.character(HHrankM_lauren$id[i])==as.character(behav$id))} )
idxM_lauren = data.frame(matrix(unlist(idx), nrow=length(idx), byrow=T)); colnames(idxM_lauren)="index"
behav$rank[idxM_lauren$index]=HHrankM_lauren$percent

all_equal(behav,behav2,ignore_col_order = F, ignore_row_order = F)
#Most ranking for HH changed for lauren.

rm(list=ls()[! ls() %in% c("behav","behav2")])  #remove variables to avoid mistakes by using the same variable names

#Load Perc computed rank and rc

#FOR HH2016
HHrankF_perc = read.csv("Behavioral_Data/GroupHH2016_files/GroupHH2016.rankInfoPercF.csv"); names(HHrankF_perc)[1]='id' 
HHrankF_perc$id = as.character(HHrankF_perc$id)
HHrankF_perc$id <- sub("'", "", HHrankF_perc$id) #eliminate spaces in names
HHrankF_perc$id <- sub("'", "", HHrankF_perc$id) #eliminate spaces in names

HHrankM_perc = read.csv("Behavioral_Data/GroupHH2016_files/GroupHH2016.rankInfoPercM.csv"); names(HHrankM_perc)[1]='id' 
HHrankM_perc$id = as.character(HHrankM_perc$id)
HHrankM_perc$id <- sub("'", "", HHrankM_perc$id) #eliminate spaces in names
HHrankM_perc$id <- sub("'", "", HHrankM_perc$id) #eliminate spaces in names

#Replace rank generated by Perc to check if it is the same:
idx = sapply( seq_along (as.character(HHrankF_perc$id)), 
              function(i){which(as.character(HHrankF_perc$id[i])==as.character(behav$id))} )
idxF_perc = data.frame(matrix(unlist(idx), nrow=length(idx), byrow=T)); colnames(idxF_perc)="index"
behav$rank2[idxF_perc$index]=HHrankF_perc$percentrank

idx = sapply( seq_along (as.character(HHrankM_perc$id)), 
              function(i){which(as.character(HHrankM_perc$id[i])==as.character(behav$id))} )
idxM_perc = data.frame(matrix(unlist(idx), nrow=length(idx), byrow=T)); colnames(idxM_perc)="index"
behav$rank2[idxM_perc$index]=HHrankM_perc$percentrank

#Assess difference in ranking between methods
diffPercRank = abs(behav$rank2 - behav2$rank2)
total_meSam =  sum(diffPercRank, na.rm = T)/length(which(!is.na(diffPercRank)))
diffPerc2LaurenRank_me = abs(behav$rank2 - behav$rank)
total_me = sum(diffPerc2LaurenRank_me, na.rm = T)/length(which(!is.na(diffPerc2LaurenRank_me)))
diffPerc2LaurenRank_sam = abs(behav2$rank2 - behav2$rank)
total_sam = sum(diffPerc2LaurenRank_sam, na.rm = T)/length(which(!is.na(diffPerc2LaurenRank_sam)))
#How I generated ranks and how sam generated rank yields quite different results (on average 30% difference).

#Complete and Replace RC generated by Perc to check if it is the same:
behav$rc[idxF_perc$index]=HHrankF_perc$rc
behav$rc[idxM_perc$index]=HHrankM_perc$rc

rm(list=ls()[! ls() %in% c("behav","behav2")])  #remove variables to avoid mistakes by using the same variable names

#FOR KK2017
HHrankF_perc = read.csv("Behavioral_Data/GroupKK2017_files/GroupKK2017.rankInfoPercF.csv"); names(HHrankF_perc)[1]='id' 
HHrankF_perc$id = as.character(HHrankF_perc$id)
HHrankF_perc$id <- sub("'", "", HHrankF_perc$id) #eliminate spaces in names
HHrankF_perc$id <- sub("'", "", HHrankF_perc$id) #eliminate spaces in names

HHrankM_perc = read.csv("Behavioral_Data/GroupKK2017_files/GroupKK2017.rankInfoPercM.csv"); names(HHrankM_perc)[1]='id' 
HHrankM_perc$id = as.character(HHrankM_perc$id)
HHrankM_perc$id <- sub("'", "", HHrankM_perc$id) #eliminate spaces in names
HHrankM_perc$id <- sub("'", "", HHrankM_perc$id) #eliminate spaces in names

#Replace rank generated by Perc to check if it is the same:
idx = sapply( seq_along (as.character(HHrankF_perc$id)), 
              function(i){which(as.character(HHrankF_perc$id[i])==as.character(behav$id))} )
idxF_perc = data.frame(matrix(unlist(idx), nrow=length(idx), byrow=T)); colnames(idxF_perc)="index"
behav$rank2[idxF_perc$index]=HHrankF_perc$percentrank

idx = sapply( seq_along (as.character(HHrankM_perc$id)), 
              function(i){which(as.character(HHrankM_perc$id[i])==as.character(behav$id))} )
idxM_perc = data.frame(matrix(unlist(idx), nrow=length(idx), byrow=T)); colnames(idxM_perc)="index"
behav$rank2[idxM_perc$index]=HHrankM_perc$percentrank

#2. Complete and Replace RC generated by Perc to check if it is the same:
behav$rc[idxF_perc$index]=HHrankF_perc$rc
behav$rc[idxM_perc$index]=HHrankM_perc$rc

diffrc = abs(behav$rc - behav2$rc)
total_meSam =  sum(diffrc, na.rm = T)/length(which(!is.na(diffrc)))
#How I generated rc and how sam generated rc yields similar result (on average .08% difference)

rm(list=ls()[! ls() %in% c("behav","behav2")])  #remove variables to avoid mistakes by using the same variable names

#3. Add Proximity & Agonistic interaction info
#Load & add proximity centrality (eigenvector)
behav$eigen.pr=NA
HHproxWeig = read.csv("Behavioral_Data/GroupHH2016_files/GroupHH2016.weigen_prox.csv"); names(HHproxWeig)[1]='id' 
HHproxWeig$id = as.character(HHproxWeig$id)
HHproxWeig$id <- sub("'", "", HHproxWeig$id) #eliminate spaces in names
HHproxWeig$id <- sub("'", "", HHproxWeig$id) #eliminate spaces in names

idx = sapply( seq_along (as.character(HHproxWeig$id)), 
              function(i){which(as.character(HHproxWeig$id[i])==as.character(behav$id))} )
idx_Weig = data.frame(matrix(unlist(idx), nrow=length(idx), byrow=T)); colnames(idx_Weig)="index"
behav$eigen.pr[idx_Weig$index]=HHproxWeig$eigen_pr

rm(list=ls()[! ls() %in% c("behav","behav2")]) #remove variables to avoid mistakes by using the same variable names

HHproxWeig = read.csv("Behavioral_Data/GroupKK2017_files/GroupKK2017.weigen_prox.csv"); names(HHproxWeig)[1]='id' 
HHproxWeig$id = as.character(HHproxWeig$id)
HHproxWeig$id <- sub("'", "", HHproxWeig$id) #eliminate spaces in names
HHproxWeig$id <- sub("'", "", HHproxWeig$id) #eliminate spaces in names

idx = sapply( seq_along (as.character(HHproxWeig$id)), 
              function(i){which(as.character(HHproxWeig$id[i])==as.character(behav$id))} )
idx_Weig = data.frame(matrix(unlist(idx), nrow=length(idx), byrow=T)); colnames(idx_Weig)="index"
behav$eigen.pr[idx_Weig$index]=HHproxWeig$eigen_pr

#Load & add proximity weighted degree
behav$Wdeg.pr =NA
HHproxWdeg = read.csv("Behavioral_Data/GroupHH2016_files/GroupHH2016.wdeg_prox.csv"); names(HHproxWdeg)[1]='id' 
HHproxWdeg$id = as.character(HHproxWdeg$id)
HHproxWdeg$id <- sub("'", "", HHproxWdeg$id) #eliminate spaces in names
HHproxWdeg$id <- sub("'", "", HHproxWdeg$id) #eliminate spaces in names

idx = sapply( seq_along (as.character(HHproxWdeg$id)), 
              function(i){which(as.character(HHproxWdeg$id[i])==as.character(behav$id))} )
idx_Wdeg = data.frame(matrix(unlist(idx), nrow=length(idx), byrow=T)); colnames(idx_Wdeg)="index"
behav$Wdeg.pr[idx_Wdeg$index]=HHproxWdeg$wdeg_prox

rm(list=ls()[! ls() %in% c("behav","behav2")]) #remove variables to avoid mistakes by using the same variable names

HHproxWdeg = read.csv("Behavioral_Data/GroupKK2017_files/GroupKK2017.Wdeg_prox.csv"); names(HHproxWdeg)[1]='id' 
HHproxWdeg$id = as.character(HHproxWdeg$id)
HHproxWdeg$id <- sub("'", "", HHproxWdeg$id) #eliminate spaces in names
HHproxWdeg$id <- sub("'", "", HHproxWdeg$id) #eliminate spaces in names

idx = sapply( seq_along (as.character(HHproxWdeg$id)), 
              function(i){which(as.character(HHproxWdeg$id[i])==as.character(behav$id))} )
idx_Wdeg = data.frame(matrix(unlist(idx), nrow=length(idx), byrow=T)); colnames(idx_Wdeg)="index"
behav$Wdeg.pr[idx_Wdeg$index]=HHproxWdeg$wdeg_prox

#Load received aggression weighted indegree
HHaggWDeg = read.csv("Behavioral_Data/GroupHH2016_files/GroupHH2016.windeg_agg.csv"); names(HHaggWDeg)[1]='id' 
HHaggWDeg$id = as.character(HHaggWDeg$id)
HHaggWDeg$id <- sub("'", "", HHaggWDeg$id) #eliminate spaces in names
HHaggWDeg$id <- sub("'", "", HHaggWDeg$id) #eliminate spaces in names

behav$Windeg.agg = NA
idx = sapply( seq_along (as.character(HHaggWDeg$id)), 
              function(i){which(as.character(HHaggWDeg$id[i])==as.character(behav$id))} )
idx_Wdeg = data.frame(matrix(unlist(idx), nrow=length(idx), byrow=T)); colnames(idx_Wdeg)="index"
behav$Windeg.agg[idx_Wdeg$index]=HHaggWDeg$Windeg_agg

rm(list=ls()[! ls() %in% c("behav","behav2")]) #remove variables to avoid mistakes by using the same variable names

HHaggWDeg = read.csv("Behavioral_Data/GroupKK2017_files/GroupKK2017.windeg_agg.csv"); names(HHaggWDeg)[1]='id' 
HHaggWDeg$id = as.character(HHaggWDeg$id)
HHaggWDeg$id <- sub("'", "", HHaggWDeg$id) #eliminate spaces in names
HHaggWDeg$id <- sub("'", "", HHaggWDeg$id) #eliminate spaces in names

idx = sapply( seq_along (as.character(HHaggWDeg$id)), 
              function(i){which(as.character(HHaggWDeg$id[i])==as.character(behav$id))} )
idx_Wdeg = data.frame(matrix(unlist(idx), nrow=length(idx), byrow=T)); colnames(idx_Wdeg)="index"
behav$Windeg.agg[idx_Wdeg$index]=HHaggWDeg$Windeg_agg

rm(list=ls()[! ls() %in% c("behav","behav2")]) #remove variables to avoid mistakes by using the same variable names

write.csv(behav,'behav_KK2017_HH2016.csv')